- name: AnsibleDocker integration
  hosts: webserver
  become: true
  become_user: root
  vars:
    image_name: edu123/myimagejenkins:latest  # Update with your Docker image name
  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run the image to deploy container
      docker_container:
        name: mycontainer
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
