- name: AnsibleDocker integration
  hosts: webserver
  become: true
  become_user: root
  vars:
    image_name: edu123/myimagejenkins:latest  # Update with your Docker image name
  tasks:
    - name: Install multiple packages on host server
      package: name={{item}}    state=present
      loop:
       - git
       - docker
       - tree
    - name: Start docker service
      service: name=docker state=started
      
    - name: Install Python pip
      package:
        name: python3-pip
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Docker Python library
      pip:
        name: docker
        state: present
    - name: Pull Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run the image to deploy container
      docker_container:
        name: mycontainer
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
